# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: é™ˆå¯Œä¸œ
title: ğŸš€ AIäº§å“ç»ç†ï½œå¼€å‘è€…ï½œåˆ›ä¸šè€…
email: baird0917@163.com
website: https://github.com/ptonlix

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: CyberFD
github_username: ptonlix
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: CyberFD
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtCyberFDb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: å¾®ä¿¡
    icon: fab fa-weixin
    url: http://cdn.oyster-iot.cloud/202505231802103.png
  - title: çŸ¥ä¹
    icon: fab fa-zhihu
    url: https://www.zhihu.com/people/baird-66

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  ğŸ‘‹ Hi, æˆ‘å«é™ˆå¯Œä¸œ  
  ä¸€ä¸ªAIäº§å“ç»ç†: ä¸“æ³¨äºAI Agentæµç¨‹ç®¡ç† ï½œ çŸ¥è¯†åº“ç®¡ç†å’Œåˆ›é€    
  ä¸€ä¸ªè½¯ä»¶å¼€å‘è€…: ä¿¡ä»°å¼€æºï¼Œä¸ºä¸–ç•Œè´¡çŒ®è‡ªå·±çš„ä»£ç , ç•™ä¸‹è‡ªå·±çš„è¶³è¿¹  
  ä¸€ä¸ªåˆ›ä¸šè€…: ç”¨äº§å“çµæ„Ÿå¼•é¢†ä¸šåŠ¡åˆ›æ–°ï¼Œç”¨æŠ€æœ¯é©±åŠ¨çµæ„Ÿè½åœ°å‘å±•  
  âš¡ï¸ ä½œå“: <mark>GoHumanLoop</mark> | <mark>å¸é˜…DeepReadå¼€æºç³»åˆ—</mark>  
  ğŸ—“ å‡ºç”Ÿå¹´æœˆ: **1994.9.17** ğŸ© æ¯•ä¸šé™¢æ ¡: **æ­å·ç”µå­ç§‘æŠ€å¤§å­¦**

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GoHumanLoop
        link: github.com/ptonlix/gohumanloop
        # link_text: Project Website
        additional_links:
          - title: ptonlix/gohumanloop
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop
          - title: ptonlix/gohumanloop-examples
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-examples
          - title: ptonlix/gohumanloop-wework
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-wework
          - title: ptonlix/gohumanloop-feishu
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-feishu
        quote: >
          ğŸ’¯ Perfecting AI workflows with human intelligence
        description: | # this will include new lines to allow paragraphs
          ã€ŒGoHumanLoopã€æ˜¯ä¸€ä¸ªPythonåº“ï¼Œä½¿AI Agentèƒ½å¤Ÿåœ¨å…³é”®é˜¶æ®µåŠ¨æ€è¯·æ±‚äººç±»è¾“å…¥ï¼ˆæ‰¹å‡†/åé¦ˆ/å¯¹è¯ï¼‰ã€‚æˆ‘åšè¿™ä¸ªé¡¹ç›®æ˜¯ä¸ºäº†è®©AI Agentä¸äººæ›´å¥½ååŒå·¥ä½œï¼Œç¡®ä¿Agentå§‹ç»ˆä¸äººç±»å¯¹é½ï¼Œæä¾›æ›´å®‰å…¨ã€æ›´å¯é çš„AIæœåŠ¡ã€‚
      - layout: top-middle
        title: å¸é˜…DeepRead
        link: https://dread.run/
        additional_links:
          - title: äº§å“ä»‹ç»
            icon: fab fa-stack-overflow
            url: https://uafzaub8s8.feishu.cn/wiki/RP0Swx7RtiFn8ekZ93xcaC2VnJb
          - title: LangChain-SearXNG
            icon: fab fa-github
            url: https://github.com/ptonlix/LangChain-SearXNG
          - title: LangChain-Emoji
            icon: fab fa-github
            url: https://github.com/ptonlix/LangChain-Emoji
        quote: >
          è¿›å…¥æ™ºèƒ½é˜…è¯»æ—¶ä»£ï¼Œäº«å—æ‰¹é˜…å¥æŠ˜ä¹è¶£
        description: |
          ã€Œå¸é˜…ã€æ˜¯ä¸€æ¬¾ä¸ªäººä¸“å±çŸ¥è¯†ç®¡ç†ä¸åˆ›é€ çš„ AI Native äº§å“ä¸ºç”¨æˆ·æ‰“é€ ä¸€ä½ä¸“å±çš„ä¾è¯»åŠ©ç†ï¼Œå¸®åŠ©ç”¨æˆ·æå‡è·å–çŸ¥è¯†æ•ˆç‡å’Œå‘æŒ¥åˆ›é€ åŠ›è®©ç”¨æˆ·æ›´å¥½åœ°å»ç§¯ç´¯çŸ¥è¯†ã€ç®¡ç†çŸ¥è¯†ã€è¿ç”¨çŸ¥è¯†ã€‚

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: æ–°å¥¥é›†å›¢-æ–°ç»
        link: https://www.enowa.cn
        # link_text: boringcompany.com
        sub_title: äº§å“ç»ç†
        caption: 2022 - è‡³ä»Š
        quote: >
          åŸºäºæ–°ç»æ—…æ¸¸åœºæ™¯,æ„å»ºå“‡é€”æ–‡æ—…æ™ºèƒ½æ¨¡å‹Waa-GPT,é‡æ„éœ€ä¾›é“¾æ¥ä¸æœåŠ¡æ¨¡å¼æ¨åŠ¨äº§ä¸šæ™ºèƒ½åŒ–å‡çº§
        description: | # this will include new lines to allow paragraphs
          ä½œä¸ºäº§å“ç»ç†ï¼Œä¸»è¦è´Ÿè´£åŒ—æµ·å›½é™…å®¢è¿æ¸¯åŠæ¶ æ´²å²›ç›¸å…³ä¼ä¸šæ™ºèƒ½äº§å“ï¼ˆæ—…æ¸¸æ™ºä¼´ã€ç»è¥æ™ºä¼´å’Œå¹³å°äº§å“ï¼‰è®¾è®¡ï¼Œä¸»å¯¼æ¨åŠ¨ç›¸å…³äº§å“çš„ç ”å‘ã€æµ‹è¯•ã€éƒ¨ç½²å’Œç»´æŠ¤  
          äº§å“æ¯å¹´æœåŠ¡è¶…220ä¸‡+æ¸¸å®¢å’Œ500+ç”Ÿæ€å•†å®¶
      - layout: left
        title: æ·±ä¿¡æœ
        link: https://www.sangfor.com.cn/
        # link_text: boringcompany.com
        sub_title: ç ”å‘å·¥ç¨‹å¸ˆ ï½œ äº§å“ç»ç†
        caption: 2018 - 2022
        quote: >
          è‡´åŠ›äºæ‰¿è½½å„è¡Œä¸šç”¨æˆ·æ•°å­—åŒ–ã€æ™ºèƒ½åŒ–è½¬å‹è¿‡ç¨‹ä¸­çš„åŸºçŸ³æ€§å·¥ä½œï¼Œä»è€Œè®©æ¯ä¸ªç”¨æˆ·çš„æ•°å­—åŒ–æ›´ç®€å•ã€æ›´å®‰å…¨ã€‚
        description: | # this will include new lines to allow paragraphs
          ä½œä¸ºç ”å‘å·¥ç¨‹å¸ˆ,è´Ÿè´£å®‰å…¨ç»„ç½‘äº§å“SDWANæ™ºèƒ½è·¯ç”±å™¨4.0ç³»åˆ—ç‰ˆæœ¬ã€å®‰å…¨æœåŠ¡Centraläº‘å›¾äº§å“çš„åå°æ¶æ„å®ç°  
          ä½œä¸ºäº§å“ç»ç†ï¼Œè´Ÿè´£äº§å“çš„éœ€æ±‚åˆ†æã€è®¾è®¡å’Œæ–‡æ¡£ç¼–å†™   
          äº§å“å‘è´§è¶…3ä¸‡+ï¼ŒæœåŠ¡äº¬ä¸œã€é¡ºä¸°ã€è”åè¶…å¸‚ã€ å·¥å•†é“¶è¡Œç­‰ä¼ä¸šå®¢æˆ·

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: æ­å·ç”µå­ç§‘æŠ€å¤§å­¦
        caption: 2013 - 2017
        sub_title: ç”µå­ä¿¡æ¯å·¥ç¨‹ - æœ¬ç§‘
        quote: >
          å­¦æ ¡åˆ›åŠäº1956å¹´, æµ™æ±Ÿçœé«˜æ°´å¹³å¤§å­¦å»ºè®¾é«˜æ ¡ - "ç¬ƒå­¦åŠ›è¡Œã€å®ˆæ­£æ±‚æ–°â€
        description: |
          æ„Ÿè°¢å¤§å­¦æœŸé—´ï¼Œå…»æˆæ¢ç´¢æœªçŸ¥çš„ä¹ æƒ¯ï¼Œä¸æ–­å­¦ä¹ çŸ¥è¯†å’Œæ‹“å®½è‡ªå·±çš„èƒ½åŠ›è¾¹ç•Œã€‚

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      é™¤äº†AIå’Œä»£ç ä¹‹å¤–ï¼Œæˆ‘è¿˜æœ‰ä¸€äº›å…¶ä»–çš„å…´è¶£çˆ±å¥½ï¼š
      - ğŸ€ ç¯®çƒ ä¸‰åˆ†å¾ˆå‡†
      - ğŸ“– é˜…è¯» é˜³æ˜å¿ƒå­¦ ï½œ ç§‘æŠ€äººæ–‡
      - ğŸ® æ¸¸æˆ Streamï½œPS5ï½œSwitch
      - ğŸ“· è®°å½•ç¾å¥½ç”Ÿæ´»

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
