# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: é™ˆå¯Œä¸œ
title: ğŸš€ AIäº§å“ç»ç†ï½œå¼€å‘è€…ï½œåˆ›ä¸šè€…
email: baird0917@163.com
website: https://github.com/ptonlix

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: CyberFD
github_username: ptonlix
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: CyberFD
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtCyberFDb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: å¾®ä¿¡
    icon: fab fa-weixin
    url: http://cdn.oyster-iot.cloud/202505231802103.png
  - title: çŸ¥ä¹
    icon: fab fa-zhihu
    url: https://www.zhihu.com/people/baird-66

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  æˆ‘å«é™ˆå¯Œä¸œ  
  ä¸€ä¸ªAIäº§å“ç»ç†: ä¸“æ³¨äºAI Agentæµç¨‹ç®¡ç† ï½œ çŸ¥è¯†åº“ç®¡ç†å’Œåˆ›é€    
  ä¸€ä¸ªè½¯ä»¶å¼€å‘è€…: ä¿¡ä»°å¼€æºï¼Œä¸ºä¸–ç•Œè´¡çŒ®è‡ªå·±çš„ä»£ç , ç•™ä¸‹è‡ªå·±çš„è¶³è¿¹  
  ä¸€ä¸ªåˆ›ä¸šè€…: ç”¨äº§å“çµæ„Ÿå¼•å¯¼ä¸šåŠ¡åˆ›æ–°ï¼Œç”¨æŠ€æœ¯é©±åŠ¨çµæ„Ÿè½åœ°å‘å±•  
  âš¡ï¸ ä½œå“: <mark>GoHumanLoop</mark> | <mark>å¸é˜…DReadå¼€æºç³»åˆ—</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GoHumanLoop
        link: github.com/ptonlix/gohumanloop
        # link_text: Project Website
        additional_links:
          - title: ptonlix/gohumanloop
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop
          - title: ptonlix/gohumanloop-examples
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-examples
          - title: ptonlix/gohumanloop-wework
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-wework
          - title: ptonlix/gohumanloop-feishu
            icon: fab fa-github
            url: github.com/ptonlix/gohumanloop-feishu
        quote: >
          ğŸ’¯ Perfecting AI workflows with human intelligence
        description: | # this will include new lines to allow paragraphs
          GoHumanLoopï¼šæ˜¯ä¸€ä¸ªPythonåº“ï¼Œä½¿AI Agentèƒ½å¤Ÿåœ¨å…³é”®é˜¶æ®µåŠ¨æ€è¯·æ±‚äººç±»è¾“å…¥ï¼ˆæ‰¹å‡†/åé¦ˆ/å¯¹è¯ï¼‰ã€‚æˆ‘åšè¿™ä¸ªé¡¹ç›®æ˜¯ä¸ºäº†è®©AI Agentä¸äººæ›´å¥½ååŒå·¥ä½œï¼Œç¡®ä¿Agentå§‹ç»ˆä¸äººç±»å¯¹é½ï¼Œæä¾›æ›´å®‰å…¨ã€æ›´å¯é çš„AIæœåŠ¡ã€‚
      - layout: top-middle
        title: å¸é˜…DeepRead
        link: https://dread.run/
        additional_links:
          - title: äº§å“ä»‹ç»
            icon: fab fa-stack-overflow
            url: https://uafzaub8s8.feishu.cn/wiki/RP0Swx7RtiFn8ekZ93xcaC2VnJb
          - title: LangChain-SearXNG
            icon: fab fa-github
            url: https://github.com/ptonlix/LangChain-SearXNG
          - title: LangChain-Emoji
            icon: fab fa-github
            url: https://github.com/ptonlix/LangChain-Emoji
        quote: >
          è¿›å…¥æ™ºèƒ½é˜…è¯»æ—¶ä»£ï¼Œäº«å—æ‰¹é˜…å¥æŠ˜ä¹è¶£
        description: |
          ã€Œå¸é˜…ã€æ˜¯ä¸€æ¬¾ä¸ªäººä¸“å±çŸ¥è¯†ç®¡ç†ä¸åˆ›é€ çš„ AI Native äº§å“ä¸ºç”¨æˆ·æ‰“é€ ä¸€ä½ä¸“å±çš„ä¾è¯»åŠ©ç†ï¼Œå¸®åŠ©ç”¨æˆ·æå‡è·å–çŸ¥è¯†æ•ˆç‡å’Œå‘æŒ¥åˆ›é€ åŠ›è®©ç”¨æˆ·æ›´å¥½åœ°å»ç§¯ç´¯çŸ¥è¯†ã€ç®¡ç†çŸ¥è¯†ã€è¿ç”¨çŸ¥è¯†.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
